### ISSUE TITLE
How to call in Java

### ISSUE THREAD

**Issue by akash55** [mddanishansari/html-to-pdf-convertor#1]
How to call in Java

**Comment by mddanishansari** [comment]
This is how you would use in Java

```java
HtmlToPdfConvertor htmlToPdfConvertor = new HtmlToPdfConvertor(context);

htmlToPdfConvertor.setBaseUrl("file:///android_asset/"); // optionally set base URL

File pdfLocation = new File(".."); // where the PDF will be saved
String htmlString = ".."; // html string that is to be converted

htmlToPdfConvertor.convert(
        pdfLocation,
        htmlString, new Function1<Exception, Unit>() {
            @Override
            public Unit invoke(Exception e) {
                e.printStackTrace();
                return Unit.INSTANCE;
            }
        }, new Function1<File, Unit>() {
            @Override
            public Unit invoke(File pdfFile) {
                // PDF has been generated at pdfFile
                return Unit.INSTANCE;
            }
        });
```

You can also replace callbacks with Lambda
```java
htmlToPdfConvertor.convert(
        pdfLocation,
        htmlString, e -> {
            e.printStackTrace();
            return Unit.INSTANCE;
        }, pdfFile -> {
            // PDF has been generated at pdfFile
            return Unit.INSTANCE;
        });
```

Library has been written in Kotlin and uses [High-order functions](https://kotlinlang.org/docs/lambdas.html) for the callback and this [link](https://stackoverflow.com/a/56368792/3486601) describes how to use High-order function in Java

**Comment by akash55** [comment]
htmlString, new Function1<Exception, Unit>() {...

Here, what is Function1 ?

**Comment by mddanishansari** [comment]
It's part of the Kotlin JVM library. Function1 indicates lambda function which takes 1 argument, Function2 indicates lambda function which takes 2 argument and so on

Take a look at below link for more detail
https://github.com/JetBrains/kotlin/blob/master/spec-docs/function-types.md#function0-function1--types

**Comment by akash55** [comment]
Ok thanks, actually not familiar with Kotlin

**Comment by mddanishansari** [comment]
Alright, no problem
