### ISSUE TITLE
how to load image from drawable ?

### ISSUE THREAD

**Issue by sw-tt-kushanshah** [mddanishansari/html-to-pdf-convertor#3]
hi,

i have to load image from drawable in below code of HTML.

  <td style="width:130px;height:65px;border-right:#d7d7d7 solid 1px;background-color:#ffffff;text-align:center;vertical-align:middle;">
    	<img src="images/logo-01.jpg" width="99" alt="">
    </td>
    <td style="width:130px;height:65px;border-right:#d7d7d7 solid 1px;background-color:#ffffff;text-align:center;vertical-align:middle;">
    	<img src="images/logo-02.jpg" width="99" alt="">
    </td>
    <td style="width:130px;height:65px;border-right:#d7d7d7 solid 1px;background-color:#ffffff;text-align:center;vertical-align:middle;">
    	<img src="images/logo-03.jpg" width="99" alt="">
    </td>

how can i load? 

please help!!!!! 

Thanks in adavance

**Comment by mddanishansari** [comment]
Actually, you can't do that. You'll have to use assets for that. Check out the sample project

**Comment by sw-tt-kushanshah** [comment]
@mddanishansari  yeah i have loaded from asset described in sample app.

thank you for prompt response
